ui_print ""
ui_print "================================================"
ui_print "     AFWall Boot AntiLeak  v2.2.2"
ui_print "================================================"
ui_print "  Blocks ALL traffic at kernel level during"
ui_print "  early boot via iptables raw/filter table."
ui_print "  Block released ONLY after AFWall+ rules"
ui_print "  are confirmed active in iptables."
ui_print "================================================"
ui_print ""
ui_print "  Supports: Android 8+ / Magisk >= 20.4"
ui_print ""
ui_print "================================================"
ui_print "  IMPORTANT: Remove any other antileak scripts"
ui_print "  from /data/adb/service.d/ before rebooting."
ui_print "  Legacy scripts are detected and removed"
ui_print "  automatically on first boot."
ui_print "================================================"
ui_print ""

IC_CONTEXT=installer
. "$MODPATH/bin/installer_config.sh"
ic_run_config_selection "install"

ui_print ""
ui_print "================================================"
ui_print "  BEFORE REBOOTING: Configure AFWall+"
ui_print "================================================"
ui_print ""
ui_print "  Open AFWall+ and set the following:"
ui_print ""
ui_print "  [REQUIRED]"
ui_print "  1. Fix Startup Data Leak → DISABLE"
ui_print "     (this module replaces it)"
ui_print "  2. Active Rules / Firewall on boot → ENABLE"
ui_print "     (required for this module to release)"
ui_print ""
ui_print "  [RECOMMENDED]"
ui_print "  3. Startup Delay → set to 0"
ui_print "     (module covers the full pre-boot window)"
ui_print "  4. IPv6 support → ENABLE"
ui_print "     (module protects both IPv4 + IPv6)"
ui_print "  5. Apply your app firewall rules at least once"
ui_print "     (AFWall must have active rules to detect)"
ui_print ""
ui_print "  [POTENTIAL CONFLICTS]"
ui_print "  Remove any other antileak scripts from:"
ui_print "    /data/adb/service.d/"
ui_print "    /data/adb/post-fs-data.d/"
ui_print "  (module auto-cleans known legacy scripts)"
ui_print ""
ui_print "================================================"
ui_print "  Config: /data/adb/AFWall-Boot-AntiLeak/config.sh"
ui_print "  Reconf: sh \$MODDIR/reconfigure.sh"
ui_print "  Logs:   /data/adb/AFWall-Boot-AntiLeak/logs/boot.log"
ui_print "================================================"
ui_print ""
