ui_print ""
ui_print "================================================"
ui_print "     AFWall Boot AntiLeak  v5.0.0"
ui_print "================================================"
ui_print "  Fast fail-closed netfilter handoff model:"
ui_print "  post-fs-data hard block + service repair"
ui_print "  AFWall graph checks start immediately;"
ui_print "  unlock only affects diagnostics/restore hints."
ui_print "================================================"
ui_print ""

ui_print "  Supports: Android 10+ / Magisk >= 27.0"
ui_print ""
ui_print "================================================"
ui_print "  IMPORTANT: Remove any other antileak scripts"
ui_print "  from /data/adb/service.d/ before rebooting."
ui_print "================================================"
ui_print ""

IC_CONTEXT=installer
. "$MODPATH/bin/installer_config.sh"
ic_run_config_selection "install"

ui_print ""
ui_print "================================================"
ui_print "  BEFORE REBOOTING: Configure AFWall+"
ui_print "================================================"
ui_print ""
ui_print "  Open AFWall+ and set the following:"
ui_print ""
ui_print "  [REQUIRED]"
ui_print "  1. Fix Startup Data Leak → DISABLE"
ui_print "     (this module replaces it)"
ui_print "  2. Active Rules / Firewall on boot → ENABLE"
ui_print "     (required for this module to release)"
ui_print ""
ui_print "  [RECOMMENDED]"
ui_print "  3. Startup Delay → set to 0"
ui_print "     (module covers the full pre-boot window)"
ui_print "  4. IPv6 support → ENABLE"
ui_print "     (module protects both IPv4 + IPv6)"
ui_print "  5. Apply your app firewall rules at least once"
ui_print "     (AFWall must have active rules to detect)"
ui_print ""
ui_print "  - WATCHDOG_POLICY uses: block or unblock"
ui_print "  - Family release no longer waits for unlock"
ui_print "  - Transport checks only stage radio/service restore"
ui_print ""
ui_print "  [POTENTIAL CONFLICTS]"
ui_print "  Remove any other antileak scripts from:"
ui_print "    /data/adb/service.d/"
ui_print "    /data/adb/post-fs-data.d/"
ui_print ""
ui_print "================================================"
ui_print "  Config: $MODPATH/config.sh + config.local.sh"
ui_print "  Reconf: sh $MODPATH/reconfigure.sh"
ui_print "  Logs:   /data/adb/AFWall-Boot-AntiLeak/logs/boot.log"
ui_print "================================================"
ui_print ""
